url: https://ggamaral.github.io

# Site settings
title: Guilherme G. Amaral
email: ggamaral@gmail.com
description: "This is my personal web page"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Guilherme_GA
  - title: facebook
    url: https://www.facebook.com/guilhermegentil
  - title: google-plus
    url: https://plus.google.com/+GuilhermeGentildoAmaral
  - title: github
    url: https://github.com/ggamaral
  - title: linkedin
    url: https://br.linkedin.com/in/guilhermegentil

# Postal address (add as many lines as necessary)
address:
  - line: Campinas, SP, Brazil

# Build settings
markdown: kramdown
permalink: pretty
